version: "3.8"

services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
    depends_on:
      - app
    networks:
      - app-network
  app:
    build:
      args:
       user: aandrews
       uid: 1000
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - .:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
